version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      SERVICE_NAME: app
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: shikkhaseba_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
